export default {
  ru: [
    {
      code: 'Backquote',
      small: 'ё',
      shift: 'Ё',
    },
    {
      code: 'Digit1',
      small: '1',
      shift: '!',
    },
    {
      code: 'Digit2',
      small: '2',
      shift: '"',
    },
    {
      code: 'Digit3',
      small: '3',
      shift: '№',
    },
    {
      code: 'Digit4',
      small: '4',
      shift: ';',
    },
    {
      code: 'Digit5',
      small: '5',
      shift: '%',
    },
    {
      code: 'Digit6',
      small: '6',
      shift: ':',
    },
    {
      code: 'Digit7',
      small: '7',
      shift: '?',
    },
    {
      code: 'Digit8',
      small: '8',
      shift: '*',
    },
    {
      code: 'Digit9',
      small: '9',
      shift: '(',
    },
    {
      code: 'Digit0',
      small: '0',
      shift: ')',
    },
    {
      code: 'Minus',
      small: '-',
      shift: '_',
    },
    {
      code: 'Equal',
      small: '=',
      shift: '+',
    },
    {
      code: 'Backspace',
      small: 'Backspace',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'Tab',
      small: 'Tab',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyQ',
      small: 'й',
      shift: 'Й',
    },
    {
      code: 'KeyW',
      small: 'ц',
      shift: 'Ц',
    },
    {
      code: 'KeyE',
      small: 'у',
      shift: 'У',
    },
    {
      code: 'KeyR',
      small: 'к',
      shift: 'К',
    },
    {
      code: 'KeyT',
      small: 'е',
      shift: 'Е',
    },
    {
      code: 'KeyY',
      small: 'н',
      shift: 'Н',
    },
    {
      code: 'KeyU',
      small: 'г',
      shift: 'Г',
    },
    {
      code: 'KeyI',
      small: 'ш',
      shift: 'Ш',
    },
    {
      code: 'KeyO',
      small: 'щ',
      shift: 'Щ',
    },
    {
      code: 'KeyP',
      small: 'з',
      shift: 'З',
    },
    {
      code: 'BracketLeft',
      small: 'х',
      shift: 'Х',
    },
    {
      code: 'BracketRight',
      small: 'ъ',
      shift: 'Ъ',
    },
    {
      code: 'Backslash',
      small: '\\',
      shift: '/',
    },
    {
      code: 'Delete',
      small: 'Del',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'CapsLock',
      small: 'CapsLock',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyA',
      small: 'ф',
      shift: 'Ф',
    },
    {
      code: 'KeyS',
      small: 'ы',
      shift: 'Ы',
    },
    {
      code: 'KeyD',
      small: 'в',
      shift: 'В',
    },
    {
      code: 'KeyF',
      small: 'а',
      shift: 'А',
    },
    {
      code: 'KeyG',
      small: 'п',
      shift: 'П',
    },
    {
      code: 'KeyH',
      small: 'р',
      shift: 'Р',
    },
    {
      code: 'KeyJ',
      small: 'о',
      shift: 'О',
    },
    {
      code: 'KeyK',
      small: 'л',
      shift: 'Л',
    },
    {
      code: 'KeyL',
      small: 'д',
      shift: 'Д',
    },
    {
      code: 'Semicolon',
      small: 'ж',
      shift: 'Ж',
    },
    {
      code: 'Quote',
      small: 'э',
      shift: 'Э',
    },
    {
      code: 'Enter',
      small: 'Enter',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ShiftLeft',
      small: 'Shift',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyZ',
      small: 'я',
      shift: 'Я',
    },
    {
      code: 'KeyX',
      small: 'ч',
      shift: 'Ч',
    },
    {
      code: 'KeyC',
      small: 'с',
      shift: 'С',
    },
    {
      code: 'KeyV',
      small: 'м',
      shift: 'М',
    },
    {
      code: 'KeyB',
      small: 'и',
      shift: 'И',
    },
    {
      code: 'KeyN',
      small: 'т',
      shift: 'Т',
    },
    {
      code: 'KeyM',
      small: 'ь',
      shift: 'Ь',
    },
    {
      code: 'Comma',
      small: 'б',
      shift: 'Б',
    },
    {
      code: 'Period',
      small: 'ю',
      shift: 'Ю',
    },
    {
      code: 'Slash',
      small: '.',
      shift: ',',
    },
    {
      code: 'ArrowUp',
      small: '&uarr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ShiftRight',
      small: 'Shift',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ControlLeft',
      small: 'Ctrl',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'MetaLeft',
      small: 'Win',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'AltLeft',
      small: 'Alt',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'Space',
      small: ' ',
      shift: ' ',
    },
    {
      code: 'AltRight',
      small: 'Alt',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowLeft',
      small: '&larr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowDown',
      small: '&darr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowRight',
      small: '&rarr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ControlRight',
      small: 'Ctrl',
      shift: null,
      isFnKey: true,
    },
  ],
  en: [
    {
      code: 'Backquote',
      small: '`',
      shift: '~',
    },
    {
      code: 'Digit1',
      small: '1',
      shift: '!',
    },
    {
      code: 'Digit2',
      small: '2',
      shift: '@',
    },
    {
      code: 'Digit3',
      small: '3',
      shift: '#',
    },
    {
      code: 'Digit4',
      small: '4',
      shift: '$',
    },
    {
      code: 'Digit5',
      small: '5',
      shift: '%',
    },
    {
      code: 'Digit6',
      small: '6',
      shift: '^',
    },
    {
      code: 'Digit7',
      small: '7',
      shift: '&',
    },
    {
      code: 'Digit8',
      small: '8',
      shift: '*',
    },
    {
      code: 'Digit9',
      small: '9',
      shift: '(',
    },
    {
      code: 'Digit0',
      small: '0',
      shift: ')',
    },
    {
      code: 'Minus',
      small: '-',
      shift: '_',
    },
    {
      code: 'Equal',
      small: '=',
      shift: '+',
    },
    {
      code: 'Backspace',
      small: 'Backspace',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'Tab',
      small: 'Tab',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyQ',
      small: 'q',
      shift: 'Q',
    },
    {
      code: 'KeyW',
      small: 'w',
      shift: 'W',
    },
    {
      code: 'KeyE',
      small: 'e',
      shift: 'E',
    },
    {
      code: 'KeyR',
      small: 'r',
      shift: 'R',
    },
    {
      code: 'KeyT',
      small: 't',
      shift: 'T',
    },
    {
      code: 'KeyY',
      small: 'y',
      shift: 'Y',
    },
    {
      code: 'KeyU',
      small: 'u',
      shift: 'U',
    },
    {
      code: 'KeyI',
      small: 'i',
      shift: 'I',
    },
    {
      code: 'KeyO',
      small: 'o',
      shift: 'O',
    },
    {
      code: 'KeyP',
      small: 'p',
      shift: 'P',
    },
    {
      code: 'BracketLeft',
      small: '[',
      shift: '{',
    },
    {
      code: 'BracketRight',
      small: ']',
      shift: '}',
    },
    {
      code: 'Backslash',
      small: '\\',
      shift: '|',
    },
    {
      code: 'Delete',
      small: 'Del',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'CapsLock',
      small: 'CapsLock',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyA',
      small: 'a',
      shift: 'A',
    },
    {
      code: 'KeyS',
      small: 's',
      shift: 'S',
    },
    {
      code: 'KeyD',
      small: 'd',
      shift: 'D',
    },
    {
      code: 'KeyF',
      small: 'f',
      shift: 'F',
    },
    {
      code: 'KeyG',
      small: 'g',
      shift: 'G',
    },
    {
      code: 'KeyH',
      small: 'h',
      shift: 'H',
    },
    {
      code: 'KeyJ',
      small: 'j',
      shift: 'J',
    },
    {
      code: 'KeyK',
      small: 'k',
      shift: 'K',
    },
    {
      code: 'KeyL',
      small: 'l',
      shift: 'L',
    },
    {
      code: 'Semicolon',
      small: ';',
      shift: ':',
    },
    {
      code: 'Quote',
      small: "'",
      shift: '"',
    },
    {
      code: 'Enter',
      small: 'Enter',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ShiftLeft',
      small: 'Shift',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'KeyZ',
      small: 'z',
      shift: 'Z',
    },
    {
      code: 'KeyX',
      small: 'x',
      shift: 'X',
    },
    {
      code: 'KeyC',
      small: 'c',
      shift: 'C',
    },
    {
      code: 'KeyV',
      small: 'v',
      shift: 'V',
    },
    {
      code: 'KeyB',
      small: 'b',
      shift: 'B',
    },
    {
      code: 'KeyN',
      small: 'n',
      shift: 'N',
    },
    {
      code: 'KeyM',
      small: 'm',
      shift: 'M',
    },
    {
      code: 'Comma',
      small: ',',
      shift: '<',
    },
    {
      code: 'Period',
      small: '.',
      shift: '>',
    },
    {
      code: 'Slash',
      small: '/',
      shift: '?',
    },
    {
      code: 'ArrowUp',
      small: '&uarr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ShiftRight',
      small: 'Shift',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ControlLeft',
      small: 'Ctrl',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'MetaLeft',
      small: 'Win',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'AltLeft',
      small: 'Alt',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'Space',
      small: ' ',
      shift: ' ',
    },
    {
      code: 'AltRight',
      small: 'Alt',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowLeft',
      small: '&larr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowDown',
      small: '&darr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ArrowRight',
      small: '&rarr;',
      shift: null,
      isFnKey: true,
    },
    {
      code: 'ControlRight',
      small: 'Ctrl',
      shift: null,
      isFnKey: true,
    },
  ],
};
